### ISSUE TITLE
Incompatible with Kodi 19 (Needs Python 3.0.0.)

### ISSUE THREAD

**Issue by heitbaum** [joshjowen/script.json-cec#10]

**Comment by Joeviocoe** [comment]
@joshjowen @YankeeGreggo @FredrikWendt 

Definitely needs to be upgraded to Python3.

I would make an attempt as my first Kodi addon, but not having an interactive Python Console environment inside Kodi, I am stuck on how to even test code.

**Comment by heitbaum** [comment]
#14 looks to be correct for the support of Kodi19 - can we please link the PR to this Issue, and pull

**Comment by Joeviocoe** [comment]
yep, the changes in #14 were enough to make it work.  Thanks.

**Comment by panton17** [comment]
Made both changes, but I still get the same error:

{
  "error": {
    "code": -32099,
    "message": "Bad client permission."
  },
  "id": 1,
  "jsonrpc": "2.0"
}

Running on CoreELEC Matrix (latest stable)

**Comment by garymm** [comment]
I think fixed by https://github.com/joshjowen/script.json-cec/pull/14
