### ISSUE TITLE
Typo in json example with in the README.txt file.

### ISSUE THREAD

**Issue by SimonEverett** [joshjowen/script.json-cec#2]
Love the plugin, and works amazing with an house fulls of Pi's Kodo and a handfull of crontab + magic other fu.

Its looks like the example json called in the readme.txt dosent work if you coppy and past, in the latest few verson of Kodio and XBMC.

http://localhost:8080/jsonrpc?request={“jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.json-cec”,”params":{"command":"activate"}},"id":1}

But if you rewrite it from scratch it dose. like:

http://localhost:8080/jsonrpc?{"jsonrpc":"2.0","method":"Addons.ExecuteAddon","params":{"addonid":"script.json-cec","params":{"command":"activate"}},"id":1}

After some hair pulling i noticed that the top staments contains two diffrent types of speech marks ” ", witch seems to calues an (00:05:33 T:1351996480   ERROR: JSONRPC: Failed to parse '{“jsonrpc":"2.0","method":"addons.ExecuteAddon","params":{"addonid":"script.json-cec”,”params":{"command":"activate"}},"id":0}'). 

Thank to the magic of Notepad++ and a few online json validator.Ive attached a screen dump that higlate the issue.
![json bug](https://cloud.githubusercontent.com/assets/5354643/12059508/8b9ce822-af54-11e5-8954-afd9199244d9.png)

**Comment by joshjowen** [comment]
Thanks, I've helped someone with this problem before and didn't realise the problem was in my own example. It should be fixed now.
