### ISSUE TITLE
Does not work with Apple TV

### ISSUE THREAD

**Issue by Astroman** [joshjowen/script.json-cec#4]
I've installed the add-on on kodi on my Apple TV and it seems to be running but my Samsung TV does not respond to its commands. I've tried several methods, including direct URL, a python script, and an Indigo plug-in with no success. No errors, but no TV control. Should this work with the Apple TV? Thanks.

**Comment by joshjowen** [comment]
No it wont work with an Apple tv. It needs a HDMI-CEC adapter like the Pulse-8 CEC adaptor or a raspberry pi which has one built in.

**Comment by Astroman** [comment]
Hmmm. I think the new Apple TV does have hdmi-cec built in since it does communicate with and control my tv via cec. Others are reporting your script stopped working with the latest Kodi release so I'm still hoping that a fix for that would help mine as well. Thanks. 

--Dave
